print("A paz vem de dentro. Não a procure fora.")
print("O que você pensa, você se torna.")
print("Mil velas podem ser acesas por uma única vela, e a vida da vela não diminui.")
print("A felicidade nunca diminui ao ser compartilhada.")
print("Não é a quantidade, mas a qualidade que importa.")
print("Você mesmo, tanto quanto qualquer pessoa no universo, merece seu amor e afeto.")
print("A mente é tudo. No que você pensa, você se transforma.")
print("Trabalhe com diligência para conquistar sua própria libertação.")
print("Um homem sensato não confia no ouro que passa por suas mãos.")
print("A raiz de todo sofrimento é o apego.")
print("Nenhuma vida é livre de dor e mágoa.")
print("Mesmo a morte não é algo a temer para quem viveu sabiamente.")
print("Melhor do que mil palavras vazias é uma única palavra que traz paz.")
print("Não persista no passado, não sonhe com o futuro, concentre a mente no presente.")
print("Assim como uma vela não pode arder sem fogo, os homens não podem viver sem uma vida espiritual.")
print("A gratidão é a memória do coração.")
print("Portanto não sejas negligente. Deixe a sabedoria guiar sua vida.")
print("Aquilo que você semeia é aquilo que você colhe.")
print("As três coisas que não podem ser escondidas: o sol, a lua e a verdade.")
print("Se você quer voar, desista de tudo que te pesa.")
print("O caminho não está no céu; o caminho está no coração.")
print("Aquietar a mente é o primeiro passo para a sabedoria.")
print("A verdadeira vitória é aquela em que ninguém perde.")
print("Cada manhã nascemos de novo. O que fazemos hoje é o que mais importa.")
print("A dúvida separa as pessoas. É um veneno que desintegra a amizade.")
print("Aquele que faz a paz é bem-aventurado.")
print("Sê uma luz para si mesmo.")
print("O passado já se foi, o futuro ainda não chegou. Só existe o momento presente.")
print("A compaixão por todos os seres é o caminho da sabedoria.")
print("Nada é permanente, exceto a mudança.")
print("Melhor conquistar a si mesmo do que vencer mil batalhas.")
print("A paciência traz consigo muitas bênçãos.")
print("Fale apenas palavras gentis, palavras que sejam ouvidas com alegria.")
print("A gota de água perfura a pedra, não pela força, mas pela persistência.")
print("Acordei às 6 da manhã para ir trabalhar.")
print("Preciso comprar 2 litros de leite no mercado.")
print("Tenho 3 reuniões marcadas para hoje.")
print("Já são 10 horas e ainda não tomei café.")
print("Comprei 5 maçãs e 2 bananas na feira.")
print("O jogo começa às 21h30 hoje.")
print("Faltam 4 dias para o fim de semana.")
print("Bebi 8 copos de água hoje.")
print("O aluguel vence no dia 10 de cada mês.")
print("Ela tem 25 anos e trabalha há 3 anos na empresa.")
print("O filme dura 2 horas e 15 minutos.")
print("Preciso enviar 6 e-mails antes do almoço.")
print("O ônibus 305 passa perto da minha casa.")
print("Vou dormir cedo hoje, lá pelas 22 horas.")
print("Comprei um caderno por 12 reais.")
print("Faltam 30 minutos para a aula começar.")
print("Ele correu 5 quilômetros essa manhã.")
print("A receita pede 200 gramas de farinha.")
print("Tenho 2 irmãos e 1 irmã.")
print("O prédio tem 12 andares.")
print("São 15h e ainda tenho 3 tarefas pendentes.")
print("Fiz 4 provas essa semana na faculdade.")
print("O carro andou 350 quilômetros no fim de semana.")
print("Recebi 7 mensagens no grupo da turma hoje.")
print("Minha aula termina às 17h40.")
print("Preciso estudar mais 2 capítulos até sexta.")